export const REQUEST_PENDING = 'REQUEST_STUDENTS_PENDING';
export const REQUEST_STUDENTS_SUCCESS = 'REQUEST_STUDENTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_STUDENTS_FAILED';
export const REQUEST_SUBJECT_SUCCESS = 'REQUEST_SUBJECT_SUCCESS';
export const SET_TIMETABLE_VIEW = 'SET_TIMETABLE_VIEW'

export const REQUEST_ATTENDANCE_LINE_SUCCESS = 'REQUEST_ATTENDANCE_LINE_SUCCESS';
export const REQUEST_ATTENDANCE_LINE_PENDING = 'REQUEST_ATTENDNACE_LINE_PENDING';
export const REQUEST_ATTENDANCE_LINE_FAILED = 'REQUEST_ATTENDANCE_LINE_FAILED';
export const REQUEST_SUBJECT_DATA = 'REQUEST_SUBJECT_DATA'

export const CHANGE_BATCH = 'CHANGE_BATCH'
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT'
export const CHANGE_SESSION = 'CHANGE_SESSION'
export const CHANGE_DATE = 'CHANGE_DATE'
export const CHANGE_REMARK = 'CHANGE_REMARK'
export const CHANGE_COURSE = 'CHANGE_COURSE'
export const CHANGE_SEMESTER = 'CHANGE_SEMESTER'
export const CHANGE_FACULTY = 'CHANGE_FACULTY'
export const CHANGE_GROUP = 'CHANGE_GROUP'
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
export const SET_SUBJECTS = 'SET_SUBJECTS'
export const CHANGE_REPORT_START_DATE = 'CHANGE_REPORT_START_DATE'
export const CHANGE_REPORT_END_DATE = 'CHANGE_REPORT_END_DATE'
export const PRINT_ATTENDANCE_REPORT = 'PRINT_ATTENDANCE_REPORT'
export const SET_REPORT_B64 = 'SET_REPORT_B64'
export const GET_SESSION_DATA = 'GET_SESSION_DATA'
export const SET_SELECTED_FACULTY = 'SET_SELECTED_FACULTY'
export const SAVE_TIMETABLE_DATA = 'SAVE_TIMETABLE_DATA'
export const SET_USER_IDENTITY = 'SET_USER_IDENTITY'
export const SET_FACULTY_TIMETABLE = 'SET_FACULTY_TIMETABLE'
export const SET_STUDENT_TIMETABLE = 'SET_STUDENT_TIMETABLE'
export const SET_EDIT_TT = 'SET_EDIT_TT'
export const SET_UID = 'SET_UID'
export const SET_SEM_DATE = 'SET_SEM_DATE'
export const PRINT_REPORT_LOADING = 'PRINT_REPORT_LOADING'
export const SET_ATTENDANCE_REPORT_DATA = 'SET_ATTENDANCE_REPORT_DATA'


